name: Sync to Hugging Face Space # The name of your workflow

on:
  push:
    branches: [ main ] # This triggers the workflow on every push to the "main" branch

jobs:
  sync:
    name: Push to Hugging Face
    runs-on: ubuntu-latest # The OS the workflow runs on
    
    steps:
    # Step 1: Checkout (download) the code from this GitHub repo
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    # Step 2: Configure Git and push to Hugging Face
    - name: Push to Hugging Face Hub
      env:
        # These secrets must be set in your GitHub repo settings
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_SPACE: ${{ secrets.HF_SPACE_NAME }}
      run: |
        git remote add hub "https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE"
        git push --force hub main
