name: Test & Sync to Hugging Face Space

# Trigger on pushes to main
on:
  push:
    branches: [main]

jobs:
  test-and-sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Run local model tests
      - name: Run local model tests
        id: test
        run: |
          pytest test_local_model.py

      # Step 5: Sync to Hugging Face Spaces (only if tests passed)
      - name: Push to Hugging Face Hub
        if: success()  # Only runs if previous step succeeded
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE: ${{ secrets.HF_SPACE_NAME }}
        run: |
          git remote add hub "https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE"
          git push --force hub main
